apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: cockroachdb

resources:
- service.yaml
- statefulset.yaml
- budget.yaml
- init-job.yaml
- backup.yaml
- scripts.yaml
